### ISSUE TITLE
Many warning windows regarding hibernate opened

### ISSUE THREAD

**Issue by robertoschwald** [tbrandt77/janrufmonitor#18] opened 2016-12-29 08:37 UTC
jAnrufmonitor opens many, many alert windows during OSX 10.12.2 hibernate mode.

This mode changes in OSX, as the OS suspends hibernate in the background e.g. for email fetching.
This may cause the windows to be shown.

At least show only one window, not many of them, or suppress the display of the window and state a text e.g. in the statusbar.

![alert_windows](https://cloud.githubusercontent.com/assets/1519879/21539793/587b1e8a-cdaa-11e6-8ff6-437619eb9306.png)

**Comment by tbrandt77** [comment] 2016-12-29 13:47
Can't reproduce this bug on my 10.12.2 macOS. What settings did you do for hibernating?

**Comment by robertoschwald** [comment] 2016-12-29 15:30
Hibernate HDDs: checked
Deactivate Hibernate on Network access: checked
Activate Power Nap: checked
Turn Of Monitor after: 1h 45

**Comment by robertoschwald** [comment] 2016-12-30 07:42
I've now checked the option "Do not show again". Hope that works this problem around.

**Comment by robertoschwald** [comment] 2016-12-31 11:08
This didn't help. The hibernate windows still show up when the system is woken up after hibernate.
Is there a config setting to avoid displaying this window?
This kind of notice is of no use for me, as the application does re-sync after hibernate, so hibernate does not affect the application functionality.

**Comment by robertoschwald** [comment] 2017-01-06 08:32
While attaching a debugger to the process and moving the hibernate file name back in time (to force the message), I can see that the message for the hibernate detection is displayed as a baloon, and as an alert box. Maybe this is an OSX specific swt issue as well?

**Comment by robertoschwald** [comment] 2017-01-06 08:45
At least I manage to suppress the annoying alert boxes: While debugging, I selected the "Do not show this Message" on the first occurence of the alert box. This helped at least to get rid of any further of such windows.

**Comment by tbrandt77** [comment] 2017-10-17 10:01
This issue was fixed on release 5.0.69 already

**Closed by tbrandt77** 2017-10-17 10:01 UTC
